### ISSUE TITLE
Add travis testing

### ISSUE THREAD

**Issue by jchodera** [choderalab/saltswap#4]
I just realized this repo doesn't have travis testing.

@gregoryross : It would only take me ~20 min to get that set up for this repo. Should I take a stab at that now?

**Comment by gregoryross** [comment]
Do you mind if I have a stab at this?

**Comment by jchodera** [comment]
Go for it! But we should get some travis testing going for this (any any other major projects) soon.

**Comment by gregoryross** [comment]
Great! I'll get on this tomorrow.

**Comment by jchodera** [comment]
How's this coming along?

**Comment by gregoryross** [comment]
I plan to migrate the simulation results and analysis first, so that the continuous integration tests only assess the main code.

**Comment by jchodera** [comment]
@gregoryross : How about I put this framework in place given you're short on time?

**Comment by gregoryross** [comment]
Only if you have the time! There's still a bunch of stuff I want to move out of this repo but the API and simulation code itself is pretty stable

**Comment by jchodera** [comment]
> simulation code itself is pretty stable

Travis will be the judge of that. ;)

**Comment by jchodera** [comment]
Starting this now.

**Comment by jchodera** [comment]
I've completed the implementation of travis tests in #8, but code issues need to be fixed by @gregoryross for tests to pass. I suggest merging it and then fixing the issues afterwards in a separate PR.

**Comment by gregoryross** [comment]
As stated above, this has been addressed in PR #8.
